### ISSUE TITLE
ARE jobs regularly failing

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/MED-condaenv#44]
ARE JupyterLab jobs are regularly failing using conda/are. Usually resubmitting the job works. From the logs:

```
Script starting...
Waiting for Jupyter Notebook server to open port 8944...
TIMING - Starting wait at: Wed Jul 19 08:46:51 AEST 2023
TIMING - Starting main script at: Wed Jul 19 08:46:51 AEST 2023
Loading conda/access-med-0.1
  Loading requirement: singularity
/g/data/xp65/public/apps/med_conda_scripts/access-med-0.1.d/bin/jupyter
/g/data/xp65/public/apps/med_conda_scripts/access-med-0.1.d/bin/jupyter
TIMING - Starting jupyter at: Wed Jul 19 08:46:51 AEST 2023
+ ssh-agent -- jupyter lab --config=/home/562/mgt562/ondemand/data/sys/dashboard/batch_connect/sys/jupyter/ncigadi/output/49214545-5019-49af-99b9-c6e15bf9afa8/config.py --FileContentsManager.root_dir=/home/562/mgt562/.jupyter-root
Traceback (most recent call last):
  File "/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/bin/jupyter-lab", line 6, in <module>
    from jupyterlab.labapp import main
  File "/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .handlers.announcements import (  # noqa
  File "/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/jupyterlab/handlers/announcements.py", line 14, in <module>
    from jupyter_server.base.handlers import APIHandler
  File "/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 23, in <module>
    from jupyter_events import EventLogger
  File "/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/jupyter_events/__init__.py", line 3, in <module>
    from .logger import EVENTS_METADATA_VERSION, EventLogger
  File "/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/jupyter_events/logger.py", line 13, in <module>
    from jsonschema import ValidationError
  File "/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/jsonschema/__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/jsonschema/_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "/g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/jsonschema/exceptions.py", line 12, in <module>
    import attr
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
OSError: [Errno 5] Input/output error
+ die 'ERROR: Jupyter Lab exited with non-zero code (1)'
+ MSG='ERROR: Jupyter Lab exited with non-zero code (1)'
+ '[' '!' -z 'ERROR: Jupyter Lab exited with non-zero code (1)' ']'
+ echo '<div class="error-msg">ERROR: Jupyter Lab exited with non-zero code (1)</div>'
+ kill -9 912230
-/bin/bash: line 1: 912230 Killed                  /local/spool/pbs/mom_priv/jobs/90739891.gadi-pbs.SC
++ date
+ echo 'TIMING - Finished jupyter at: Wed Jul 19 08:46:55 AEST 2023'
TIMING - Finished jupyter at: Wed Jul 19 08:46:55 AEST 2023
```

**Comment by rbeucher** [comment]
OK so what's the idea here for the fix?

**Comment by dougiesquire** [comment]
It looks to me as though updating `jsonschema>=4.18.1` should fix the problem, but that's causing the env to be unsolvable - see https://github.com/ACCESS-NRI/MED-condaenv/pull/45

**Comment by rbeucher** [comment]
OK I am closing that one
